name: helper_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  dio: null
  ffmpeg_wasm: ^1.0.3
  file_picker: null
  flutter:
    sdk: flutter
  flutter_riverpod: null
  fpdart: null
  gap: null
  google_sign_in: null
  googleapis: null
  googleapis_auth: null
  http: ^1.4.0
  shared_preferences: 

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
